### ISSUE TITLE
The screen shows black without chess scene?

### ISSUE THREAD

**Issue by leftstone2015** [WeiPhil/nbvh#3]
hi, thanks for your great work.

I am trying to run the code in my PC with the chess scene.  
Following the instructions in readme, it seems that it goes well from the log. The log as follows:

[Info] Loaded Envmap from ../nbvh/scene_data\hdris\photo_studio_loft_hall_4k.exr
[Info] Loading neural BVH from :
..//nbvh/scene_data/scenes_path_tracing/chess\nbvhs\nodes_32940_hash_18_lvl_8_tsteps_10000.nbvh...
[Info] Loaded neural LibBVH with 25249 nodes.
[Info] Deserializing network model from : ../nbvh/scene_data/scenes_path_tracing/chess\network_models\nodes_32940_hash_18_lvl_8_tsteps_10000_network.json
[Info] Done!
[Info] Done!
[Info] Done!
[Info] Added renderer : Neural BVH Renderer

But the screen shows black without chess scene, as follows:
![image](https://github.com/user-attachments/assets/fe60593a-5451-4407-8318-5cd241c53f39)

Could you help check it and tell me whether it it OK? What is next step to show the scene?

**Comment by WeiPhil** [comment]
Hi,
This looks fine.
Have you clicked on "Run inference" in the UI?
Best,
Philippe

**Comment by leftstone2015** [comment]
Thank you for replying quickly. I've just tried it. The screen still shows black, but the frame rate dropped from 1000+fps to 10-fps.

**Comment by leftstone2015** [comment]
Thank you for replying quickly. I've tried it, but the screen still goes back. By the way, the frame rate dropped for 1000+fps to 10-fps.

**Comment by leftstone2015** [comment]
Thank you for replying quickly. I've tried it, but the screen still goes back. By the way, the frame rate dropped for 1000+fps to 10-fps.

**Comment by WeiPhil** [comment]
Something is probably going wrong with the display then. Are you using the binary release or did you compile from source? If you are using the binary release I would start by building from source. I would also need info on your configuration to reproduce this (GPU + driver, Cuda version, operating system, C/C++ compiler)

**Comment by leftstone2015** [comment]
Here are the information of my PC:

1. GPU: NVIDIA GeForce RTX 3090
2. Driver：NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6
3. OS: Win11
4. cmake cmd： cmake -G "Visual Studio 17 2022" -DCMAKE_CUDA_ARCHITECTURES=86 -A x64 -B build

cmake output: 
 Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.38.33141.0
-- The CXX compiler identification is MSVC 19.38.33141.0
-- The CUDA compiler identification is NVIDIA 12.6.68

By the way, if I use -DCMAKE_CUDA_ARCHITECTURES=89,  I will get the link error of "CUDA_SYNC_CHECK".

**Comment by WeiPhil** [comment]
This is likely a mismatch between compute capabilities. Make sure to clean the build directory completely and start te compilation from scratch specifying -DCMAKE_CUDA_ARCHITECTURES=86 (a clean from scratch config and rebuild is necessary as some files might still be using 89 since you specified this). Note that your 3090 expects compute capability 86 as specified [here](https://developer.nvidia.com/cuda-gpus). If that still doesn't solve the issue I would try an older version of CUDA, e.g. 12.0 for which our build was tested.

**Comment by leftstone2015** [comment]
When I use the binary, it goes well. 

> Something is probably going wrong with the display then. Are you using the binary release or did you compile from source? If you are using the binary release I would start by building from source. I would also need info on your configuration to reproduce this (GPU + driver, Cuda version, operating system, C/C++ compiler)

**Comment by leftstone2015** [comment]
> This is likely a mismatch between compute capabilities. Make sure to clean the build directory completely and start te compilation from scratch specifying -DCMAKE_CUDA_ARCHITECTURES=86 (a clean from scratch config and rebuild is necessary as some files might still be using 89 since you specified this). Note that your 3090 expects compute capability 86 as specified [here](https://developer.nvidia.com/cuda-gpus). If that still doesn't solve the issue I would try an older version of CUDA, e.g. 12.0 for which our build was tested.

I use compute capability 86 from scratch, it does not work. The screen is black.

**Comment by leftstone2015** [comment]
Hi, can you reproduce it ?

**Comment by WeiPhil** [comment]
I have not been able to so far.. Most likely a driver or CUDA version issue since the binary release seems to work for you as well, have you tried CUDA 12.0 and a different (earlier) driver version ?

**Comment by leftstone2015** [comment]
OK, thank you. I will try the following version first: 
Cuda Compiler NVIDIA 12.0
Nvidia Driver 546.29

**Comment by leftstone2015** [comment]
NVIDIA-SMI 546.29                 Driver Version: 546.29       CUDA Version: 12.3

I have just tried the above version, it still failed, and show black window as before.

**Comment by WeiPhil** [comment]
This is very odd, this exact configuration works for me, also with an RTX3090. Have you tried running in debug mode, see if this triggers anything? Since I can't reproduce the issue here, its kinda hard to guess where the problem is coming from.

**Comment by leftstone2015** [comment]
I tested it OK, by pulled the whole repo again. Maybe some versions of sub modules are not correct.

**Comment by leftstone2015** [comment]
It's been solved by pulled the whole repo again with correct versions of sub modules.
