### ISSUE TITLE
How to apply the technique to dynamic scenes?

### ISSUE THREAD

**Issue by leftstone2015** [WeiPhil/nbvh#5]
hi, WeiPhi:
    I checked the demo, I found that it need retrain after adjusting the camera.  Is it right? If so, is it possible to apply the technique to dynamic scenes? eg: camera moving, or animation.

**Comment by WeiPhil** [comment]
Camera and light animation do not require any retraining, only rerendering, moving around an NBVH also does not require any retraining.

**Comment by leftstone2015** [comment]
When I change the camera by mouse, the Accumulated samples reset to 0, and the scene show noisy again. Is it  the expectation? When checking "Disable Neural BLAS (Reference)", the frame rate increase from 50fps to 120fps in my PC, RTX3090. Is it as expected? If so, the performance decreases with N-BVH?

**Comment by WeiPhil** [comment]
Yes this is all expected, moving the mouse restarts rendering. The reference can run faster than N-BVH when using a high ammount of BVH nodes, you can refer to the paper's table for a detailed overview of the performances.
